barcode:
  symbologies:
    code_25: Code 25
    code_25_interleaved: Code 25 Interleaved
    code_25_iata: Code 25 IATA
    code_39: Code 39
    code_93: Code 93
    code_128: Code 128
    ean_13: EAN-13
    ean_8: EAN-8
    qr_code: QR Code
